
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml